


#include "include.h"

//---------------------------------------------
// define EEPROM data size
//---------------------------------------------
SI_LOCATED_VARIABLE_NO_INIT(A0TableEEPROM[A0_TABLE_SIZE],       uint8_t, SI_SEG_CODE, A0_TABLE_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(TableLowerEEPROM[TABLE_LOWER_SIZE], uint8_t, SI_SEG_CODE, TABLE_LOWER_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table00EEPROM[TABLE00_SIZE],        uint8_t, SI_SEG_CODE, TABLE00_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table80EEPROM[TABLE80_SIZE],        uint8_t, SI_SEG_CODE, TABLE80_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table81EEPROM[TABLE81_SIZE],        uint8_t, SI_SEG_CODE, TABLE81_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table82EEPROM[TABLE82_SIZE], 		uint8_t, SI_SEG_CODE, TABLE82_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table83EEPROM[TABLE83_SIZE], 		uint8_t, SI_SEG_CODE, TABLE83_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table84EEPROM[TABLE84_SIZE], 		uint8_t, SI_SEG_CODE, TABLE84_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table86EEPROM[TABLE86_SIZE], 		uint8_t, SI_SEG_CODE, TABLE86_ADDRESS);
SI_LOCATED_VARIABLE_NO_INIT(Table87EEPROM[TABLE87_SIZE], 		uint8_t, SI_SEG_CODE, TABLE87_ADDRESS);




